### ISSUE TITLE
Error when using 0.1.31-beta

### ISSUE THREAD

**Issue by sandeepc24** [demetrixbio/FSharp.Data.Npgsql#16]
I am getting following error after updating to 0.1.31-beta

```
FSC : warning FS3005: Referenced assembly 'C:\Users\myname\.nuget\packages\fsharp.data.npgsql\0.1.31-beta\lib\netstandard2.0\FSharp.Data.Npgsql.dll' has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute' but no public type provider classes were found
```

If I go back to 0.1.29-beta I don't get this error.

**Comment by dmitry-a-morozov** [comment]
Hmm. I cannot repro this issue.
How about 0.1.30-beta? Does that work for you?

**Comment by sandeepc24** [comment]
I get same error with 0.1.30-beta.

**Comment by sandeepc24** [comment]
After updating to latest VS update I get following error

```
FSC : error FS3031: The type provider 'C:\Users\MYNAME\.nuget\packages\fsharp.data.npgsql\0.1.31-beta\lib\netstandard2.0\FSharp.Data.Npgsql.dll' reported an error: 
Assembly attribute 'TypeProviderAssemblyAttribute' refers to a designer assembly 
'FSharp.Data.Npgsql.DesignTime' which cannot be loaded or doesn't exist. 
Could not load file or assembly 'FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. 
The system cannot find the file specified. [C:\Server.fsproj] [C:\\ServerTests\ServerTests.fsproj]
```

I also created a new project and I still get the same error. 

I have checked folder `C:\Users\MYNAME\.nuget\packages\fsharp.data.npgsql\0.1.31-beta\lib\netstandard2.0\` and file `FSharp.Data.Npgsql.DesignTime` is in there.

**Comment by sandeepc24** [comment]
Did some more investigation, and the new project that I created from command line fails to build from command line, but when I open it in VS2017 and build it builds fine. Thereafter it builds fine from command line until I do `dotnet clean`.

**Comment by sandeepc24** [comment]
After cleaning the nuget cache and rebuilding the project now I am getting

```
The type provider 'FSharp.Data.Npgsql.NpgsqlProviders' reported an error: Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
```

I have `fsc.props` in my project.

**Comment by sandeepc24** [comment]
After VS 2017 latest update 0.1.29-beta has stopped working.

**Comment by sandeepc24** [comment]
Finally found that it was caused by incorrect in fsc.props. The old path was
`<FscToolPath>C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0</FscToolPath>`
and after latest V22017 it needs to be set to
`<FscToolPath>C:\Program Files (x86)\Microsoft SDKs\F#\10.1\Framework\v4.0</FscToolPath>`

**Comment by sandeepc24** [comment]
<?xml version="1.0" encoding="utf-8"?>
<Project>
  
  <PropertyGroup>
    <IsWindows Condition="'$(OS)' == 'Windows_NT'">true</IsWindows>
    <IsOSX Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))' == 'true'">true</IsOSX>
    <IsLinux Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))' == 'true'">true</IsLinux>
  </PropertyGroup>  
  <PropertyGroup Condition="'$(IsWindows)' == 'true' AND Exists('C:\Program Files (x86)\Microsoft SDKs\F#\10.1\Framework\v4.0\fsc.exe')">
    <FscToolPath>C:\Program Files (x86)\Microsoft SDKs\F#\10.1\Framework\v4.0</FscToolPath>
    <FscToolExe>fsc.exe</FscToolExe>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsOSX)' == 'true'  AND Exists('/Library/Frameworks/Mono.framework/Versions/Current/Commands/fsharpc')">
    <FscToolPath>/Library/Frameworks/Mono.framework/Versions/Current/Commands</FscToolPath>
    <FscToolExe>fsharpc</FscToolExe>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsLinux)' == 'true' AND Exists('/usr/bin/fsharpc')">
    <FscToolPath>/usr/bin</FscToolPath>
    <FscToolExe>fsharpc</FscToolExe>
  </PropertyGroup>
</Project>
