### ISSUE TITLE
PostgisGeometry error after upgrading to 0.1.35 beta

### ISSUE THREAD

**Issue by sandeepc24** [demetrixbio/FSharp.Data.Npgsql#23]
I am getting following error after upgrading to 0.1.35 beta. I am on dotnet 2.1.4.

```
 error FS3021: Unexpected exception from provided type 'FSharp.Data.Npgsql.NpgsqlConnection,Connection="DATABASE_URL_PG",Config="C:\\.../appsettings.json"+Commands+CreateCommand,CommandText"select * from addresses where id  AddressId",ResultType"2"+Table' member 'GetMethods': The type provider 'FSharp.Data.Npgsql.NpgsqlProviders' reported an error: The design-time type 'Npgsql.LegacyPostgis.PostgisGeometry' utilized by a type provider was not found in the target reference assembly set...
```

**Comment by dmitry-a-morozov** [comment]
Thanks for reporting the issue. It's bit hard to test.
Try 
https://www.nuget.org/packages/FSharp.Data.Npgsql/0.1.36-beta

**Comment by sandeepc24** [comment]
Thanks for fixing it Dmitry, I have an urgent issue to fix before I can test this, I'll let you know once I test this version.

**Comment by sandeepc24** [comment]
Apologies for the delayed response. It is still not working and I am getting same error.

**Comment by dmitry-a-morozov** [comment]
Make sure you reference `Npgsql.LegacyPostgis` package in consumption project.

**Comment by dmitry-a-morozov** [comment]
Great. 
Just curios how did you end up missing `Npgsql.LegacyPostgis` package? 
Because it's listed as explicit dependency 
https://www.nuget.org/packages/FSharp.Data.Npgsql/0.1.36-beta

Also, going forward some re-design will required to support choice between 
- NetTopologySuite
- GeoJSON
- Legacy PostGIS

**Comment by sandeepc24** [comment]
Npgsql.LegacyPostgis was never installed and it didn't install when I upgraded to 0.1.36.

**Comment by dmitry-a-morozov** [comment]
You need to add type mappers
https://github.com/demetrixbio/FSharp.Data.Npgsql/blob/master/tests/NpgsqlCmdTests.fs#L19

I realized that library should do it automatically when connection string passed into command ctor.

**Comment by dmitry-a-morozov** [comment]
no

**Comment by sandeepc24** [comment]
Thanks that fixed it.

**Comment by sandeepc24** [comment]
oops that fixed compilation only, I am still getting 
```
 Expected column "geom" of type "Npgsql.LegacyPostgis.PostgisGeometry" at position 6 (0-based indexing) but received column "geom" of type "System.String".
     at FSharp.Data.Npgsql.ISqlCommand Implementation.VerifyOutputColumns(NpgsqlDataReader cursor, DataColumn[] expectedColumns)
```

**Comment by dmitry-a-morozov** [comment]
Do you pass connection string or connection instance to a command that fails?

**Comment by sandeepc24** [comment]
connection string

**Comment by dmitry-a-morozov** [comment]
I need to post a fix to make it work.

**Comment by sandeepc24** [comment]
ok, I'll wait for your fix. Thanks.

**Comment by dmitry-a-morozov** [comment]
Try https://www.nuget.org/packages/FSharp.Data.Npgsql/0.1.38-beta

**Comment by sandeepc24** [comment]
Thanks, that fixed the issue.
